function c= bucle_exp4()
% Script para generar varias simulaciones. ¡Es importante que la función a la que se
% llama se encuentre en el mismo directorio!
c={'exp4(-30)',...
    'exp4(-25)',...
    'exp4(-20)',...
    'exp4(-15)',...
    'exp4(-10)',...
    'exp4(-5)',...
    'exp4(0)'};