function c= bucle_exp3()
% Script para generar varias simulaciones. ¡Es importante que la función a la que se
% llama se encuentre en el mismo directorio!
c={'exp3(2)',...
    'exp3(2.4)',...
    'exp3(2.8)',...
    'exp3(3)',...
    'exp3(3.3)',...
    'exp3(3.6)',...
    'exp3(4)'};
% c={'exp3(4)','exp3(4)','exp3(4)'};