function c= variasSim()
% Script para generar varias simulaciones. ¡Es importante que la función a la que se
% llama se encuentre en el mismo directorio!
c={'base(10)',...
    'base(20)',...
    'base(30)',...
    'base(40)',...
    'base(50)'};